version: '3.8'

services:
  redis-master:
    image: redis:6.2
    ports:
      - "${REDIS_MASTER_PORT}:6379"
    command: ["redis-server", "--port", "6379", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-net

  redis-replica:
    image: redis:6.2
    ports:
      - "${REDIS_REPLICA_1_PORT}:6379"
    command: [
      "redis-server",
      "--port", "6379",
      "--replicaof", "redis-master", "6379",
      "--requirepass", "${REDIS_PASSWORD}",
      "--masterauth", "${REDIS_PASSWORD}"
    ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel:
    image: redis:6.2
    ports:
      - "${REDIS_SENTINEL_1_PORT}:26379"
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
