repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--explicit-package-bases"]
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-redis

  - repo: local
    hooks:
      - id: fix-docs
        name: Documentation Auto-Fixer
        entry: python scripts/verify_docs.py --fix
        language: python
        pass_filenames: false
        types: [file]
        additional_dependencies:
          - rich>=13.0.0
          - pyyaml>=6.0.0
          - doc8>=1.1.1

      - id: check-code-blocks
        name: Code Block Validator
        entry: python scripts/validate_code_blocks.py
        language: python
        pass_filenames: false
        types: [file]
        additional_dependencies:
          - rich>=13.0.0

      - id: validate-config
        name: Configuration Validator
        entry: python scripts/validate_config.py
        language: python
        pass_filenames: false
        types: [file]
        additional_dependencies:
          - pyyaml>=6.0.0
          - pydantic>=2.0.0
