version: '3.8'

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-redis-master-1
    ports:
      - "6381:6379"
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-replica:
    image: redis:7-alpine
    container_name: redis-redis-replica-1
    ports:
      - "6382:6379"
    command: redis-server --slaveof 172.19.0.2 6379
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  sentinel1:
    image: redis:7-alpine
    container_name: redis-redis-sentinel-1-1
    ports:
      - "26379:26379"
    command: redis-sentinel /redis/sentinel.conf
    volumes:
      - ./server/tests/redis/config/sentinel1:/redis
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-net

  sentinel2:
    image: redis:7-alpine
    container_name: redis-redis-sentinel-2-1
    ports:
      - "26380:26379"
    command: redis-sentinel /redis/sentinel.conf
    volumes:
      - ./server/tests/redis/config/sentinel2:/redis
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-net

  sentinel3:
    image: redis:7-alpine
    container_name: redis-redis-sentinel-3-1
    ports:
      - "26381:26379"
    command: redis-sentinel /redis/sentinel.conf
    volumes:
      - ./server/tests/redis/config/sentinel3:/redis
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-net

networks:
  redis-net:
    name: redis_redis-net
    external: true

volumes:
  sentinel1_data:
  sentinel2_data:
  sentinel3_data:
