version: '3.8'

services:
  server:
    build:
      target: production
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./server/static:/app/static
      - ./server/media:/app/media

  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_prod_data:/data

  nginx:
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=443

volumes:
  postgres_prod_data:
  redis_prod_data:
