version: '3.8'
services:
  redis-master:
    image: redis:6.2
    command: ["redis-server", "--port", "6379"]
    ports:
      - "6379:6379"

  redis-replica:
    image: redis:6.2
    command: ["redis-server", "--port", "6379", "--replicaof", "redis-master", "6379"]
    ports:
      - "6380:6379"

  sentinel:
    image: redis:6.2
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
      - sentinel_data:/data
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    ports:
      - "26379:26379"

volumes:
  sentinel_data:
