global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/redis_recording.yml
  - /etc/prometheus/rules/redis_alerts.yml

scrape_configs:
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    metrics_path: /metrics

  - job_name: "redis_sentinel"
    static_configs:
      - targets: ["redis-exporter-sentinel:9121"]
    metrics_path: /metrics
