name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'scripts/validate_docs.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'scripts/validate_docs.py'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pyyaml rich

      - name: Validate documentation
        run: |
          python scripts/validate_docs.py

      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config: .github/workflows/markdownlint.json

  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Documentation metrics
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.github/workflows/markdownlint.json'
          args: '**.md'

      - name: Generate documentation report
        run: |
          echo "Documentation Statistics" > docs-report.txt
          echo "======================" >> docs-report.txt
          echo "Files: $(find . -name '*.md' | wc -l)" >> docs-report.txt
          echo "Total Lines: $(find . -name '*.md' -exec cat {} \; | wc -l)" >> docs-report.txt

      - name: Upload documentation report
        uses: actions/upload-artifact@v3
        with:
          name: documentation-report
          path: docs-report.txt
