name: Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-benchmark

      - name: Run Performance Tests
        run: |
          pytest tests/performance/test_rate_limiter.py \
            --benchmark-only \
            --benchmark-json=benchmark.json \
            -v

      - name: Check Performance Thresholds
        run: |
          python -c '
          import json
          with open("benchmark.json") as f:
              data = json.load(f)

          failed = False
          for bench in data["benchmarks"]:
              name = bench["name"]
              mean = bench["stats"]["mean"]

              if "single_thread" in name and mean > 0.001:
                  print(f"❌ {name}: {mean:.6f}s exceeds 1ms threshold")
                  failed = True
              elif "redis_operation" in name and mean > 0.003:
                  print(f"❌ {name}: {mean:.6f}s exceeds 3ms threshold")
                  failed = True
              elif "configuration_load" in name and mean > 0.005:
                  print(f"❌ {name}: {mean:.6f}s exceeds 5ms threshold")
                  failed = True
              else:
                  print(f"✅ {name}: {mean:.6f}s within threshold")

          exit(1 if failed else 0)
          '

      - name: Store Performance Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: benchmark.json
